### PR TITLE
COMMONSRDF-9: Bootstrap Commons site build

### PR DESCRIPTION
**Pull request by britter**
I've created an inital site for Commons RDF (shamelessly copied from Commons Lang). There are still a number of TODOs, but we can use this as a starting ground.

### CODE REVIEW

**Comment by stain** [comment]
`mvn site` works. 

But `mvn clean install` fails:
{code}
[INFO] --- license-maven-plugin:2.8:check (default) @ commons-rdf-parent ---
[INFO] Checking licenses...
[WARNING] Unknown file extension: /home/stain/src/commons-rdf/src/site/resource/download_rdf.cgi
[WARNING] Missing header in: /home/stain/src/commons-rdf/src/site/xdoc/download_rdf.xml
[WARNING] Missing header in: /home/stain/src/commons-rdf/src/changes/changes.xml
[WARNING] Missing header in: /home/stain/src/commons-rdf/src/site/xdoc/index.xml
[WARNING] Missing header in: /home/stain/src/commons-rdf/src/changes/release-notes.vm
[WARNING] Missing header in: /home/stain/src/commons-rdf/src/site/xdoc/issue-tracking.xml
[WARNING] Missing header in: /home/stain/src/commons-rdf/src/site/xdoc/mail-lists.xml
[WARNING] Missing header in: /home/stain/src/commons-rdf/src/site/site.xml
{code}

.. even though (most of) those have the correct header. Why do we have both license-maven-plugin and rat plugin?

**Comment by stain** [comment]
Looks good - will have to modify the site-deploy target, as it tries to push to:

https://svn.apache.org/repos/infra/websites/production/commons/content/proper/commons-rdf-parent

while I guess it should be to:
https://svn.apache.org/repos/asf/incubator/commonsrdf/site/trunk/
?
(https://issues.apache.org/jira/browse/INFRA-9260 is still pending)

**Comment by britter** [comment]
Hello @stain,

> .. even though (most of) those have the correct header. Why do we have both license-maven-plugin and rat plugin?

Sorry about the build failure, I only sued mvn clean site, which did not fail. My fault!
About the license-maven-plugin: I'm not sure. At commons we only use RAT. I think that's sufficient.

> while I guess it should be to: https://svn.apache.org/repos/asf/incubator/commonsrdf/site/trunk/

Yes, that's the place. Note that I've discovered a glitch in the commons skin https://issues.apache.org/jira/browse/COMMONSSITE-82 Maybe we have to modify the site.css after the site deploy. I'm currently working on the skin but that will take some time.

**Comment by stain** [comment]
Is there something in this pull request that remains relevant for COMMONSRDF-9 given that we now have the site live? (Perhaps the download stubs?) If not, are you OK to close this?

**Comment by britter** [comment]
@stain We need to figure out how to get the project reports working (see my comment on the Dev ML). But I think we can do this in a separate PR.

**Pull request closed without merging**
